"""Shared helpers for the provisioning scripts (stdlib only, no installs needed).

Files (repo root, both gitignored):
  .env                   owner-supplied tokens (SUPABASE_ACCESS_TOKEN, RENDER_API_KEY,
                         CLOUDFLARE_*), app keys (OPENAI_API_KEY, AZURE_DI_*) and LOCAL dev values.
  .env.production.local  PRODUCTION values generated by these scripts (Supabase URL/keys,
                         DATABASE_URL, CRON_SECRET, PAGES_URL, API_BASE_URL, ...). Kept apart so
                         local dev (docker compose, Vite dev server) never points at production.

Lookup order for a key: .env.production.local > .env > process environment (CI has no files).
Secret values are never printed: only names, lengths or non-secret URLs.
"""

from __future__ import annotations

import json
import os
import re
import secrets
import string
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
ENV_FILE = ROOT / ".env"
PROD_ENV_FILE = ROOT / ".env.production.local"

PROJECT_NAME = "even"                      # Supabase project + Cloudflare Pages project
RENDER_SERVICE_NAME = "even-api"
GITHUB_REPO = "GeorgePPP/bill_splitter"
DEFAULT_PAGES_URL = f"https://{PROJECT_NAME}.pages.dev"
USER_AGENT = "even-provision/1.0 (+https://github.com/GeorgePPP/bill_splitter)"

# Windows consoles default to cp1252; never crash on an arrow or a non-ASCII name.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

_LINE = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$")


# ----------------------------------------------------------------------------- env files
def read_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text(encoding="utf-8-sig").splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        m = _LINE.match(raw)
        if not m:
            continue
        key, val = m.group(1), m.group(2)
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "'\"":
            val = val[1:-1]
        values[key] = val
    return values


class Env:
    """Merged view of the env files + process env (see module docstring for precedence)."""

    def __init__(self) -> None:
        self.reload()

    def reload(self) -> None:
        self.local = read_env_file(ENV_FILE)
        self.prod = read_env_file(PROD_ENV_FILE)

    def get(self, key: str, default: str = "") -> str:
        for source in (self.prod, self.local, os.environ):
            val = source.get(key, "")
            if val.strip():
                return val.strip()
        return default

    def prod_get(self, key: str, default: str = "") -> str:
        """Only the production file, then the process env (never local dev values)."""
        for source in (self.prod, os.environ):
            val = source.get(key, "")
            if val.strip():
                return val.strip()
        return default

    def write_prod(self, updates: dict[str, str], dry_run: bool) -> None:
        changed = {k: v for k, v in updates.items() if v is not None and self.prod.get(k) != v}
        if not changed:
            print(f"  {PROD_ENV_FILE.name}: up to date")
            return
        names = ", ".join(sorted(changed))
        if dry_run:
            print(f"  [dry-run] would write to {PROD_ENV_FILE.name}: {names}")
            return
        upsert_env_file(PROD_ENV_FILE, changed)
        self.reload()
        print(f"  wrote to {PROD_ENV_FILE.name}: {names}")


def upsert_env_file(path: Path, updates: dict[str, str]) -> None:
    """Replace KEY=... lines in place (keeps comments/order) and append new keys."""
    for k, v in updates.items():
        if "\n" in v or "\r" in v:
            raise ValueError(f"{k}: multi-line values are not supported")
    lines = path.read_text(encoding="utf-8-sig").splitlines() if path.exists() else [
        "# PRODUCTION values for even, written by scripts/provision/*.py. Gitignored. Never commit.",
        "# Plain KEY=value lines (no quotes) so `docker run --env-file` reads them verbatim.",
    ]
    pending = dict(updates)
    for i, raw in enumerate(lines):
        m = _LINE.match(raw)
        if m and not raw.lstrip().startswith("#") and m.group(1) in pending:
            lines[i] = f"{m.group(1)}={pending.pop(m.group(1))}"
    lines.extend(f"{k}={v}" for k, v in pending.items())
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ----------------------------------------------------------------------------- output
def describe(value: str) -> str:
    """Safe description of a secret: never any of its characters."""
    return f"set ({len(value)} chars)" if value else "MISSING"


def random_secret(length: int = 40) -> str:
    alphabet = string.ascii_letters + string.digits  # URL/env/shell safe, no quoting needed
    return "".join(secrets.choice(alphabet) for _ in range(length))


def step(title: str) -> None:
    print(f"\n== {title}")


def die(msg: str, code: int = 1) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    raise SystemExit(code)


def require(env: Env, *keys: str, dry_run: bool = False) -> bool:
    missing = [k for k in keys if not env.get(k)]
    if not missing:
        return True
    where = f"{ENV_FILE.name} (repo root)"
    if dry_run:
        print(f"  [dry-run] {', '.join(missing)} not set in {where}; showing the plan with placeholders")
        return False
    die(f"{', '.join(missing)} not set. Add it to {where}; see .skills/DEPLOYMENT.md.")
    return False


def origin_of(url: str) -> str:
    p = urllib.parse.urlsplit(url.strip())
    return f"{p.scheme}://{p.netloc}" if p.scheme and p.netloc else url.strip().rstrip("/")


def pages_url(env: Env) -> str:
    url = env.prod_get("PAGES_URL")
    if url:
        return origin_of(url)
    print(f"  note: PAGES_URL not set yet (run cloudflare.py first); assuming {DEFAULT_PAGES_URL}")
    return DEFAULT_PAGES_URL


# ----------------------------------------------------------------------------- HTTP
class HttpError(Exception):
    def __init__(self, status: int, message: str) -> None:
        super().__init__(f"HTTP {status}: {message}")
        self.status = status
        self.message = message


def _error_message(body: Any, raw: str) -> str:
    """Short, non-secret error text from an API error body."""
    if isinstance(body, dict):
        for key in ("message", "msg", "error_description", "error"):
            if isinstance(body.get(key), str):
                return body[key][:300]
        errs = body.get("errors")
        if isinstance(errs, list) and errs:
            return "; ".join(str(e.get("message", e))[:200] if isinstance(e, dict) else str(e)[:200]
                             for e in errs[:3])
    return raw[:300]


def http(method: str, url: str, *, token: str | None = None, body: Any = None,
         headers: dict[str, str] | None = None, timeout: float = 60.0, retries: int = 2) -> tuple[int, Any]:
    """JSON request. Returns (status, parsed body). Raises HttpError for >= 400."""
    hdrs = {"Accept": "application/json", "User-Agent": USER_AGENT}
    if token:
        hdrs["Authorization"] = f"Bearer {token}"
    data = None
    if body is not None:
        data = json.dumps(body).encode()
        hdrs["Content-Type"] = "application/json"
    hdrs.update(headers or {})
    attempt = 0
    while True:
        attempt += 1
        req = urllib.request.Request(url, data=data, method=method, headers=hdrs)
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                raw = resp.read().decode("utf-8", "replace")
                return resp.status, (json.loads(raw) if raw.strip() else None)
        except urllib.error.HTTPError as exc:
            raw = exc.read().decode("utf-8", "replace")
            try:
                parsed = json.loads(raw) if raw.strip() else None
            except ValueError:
                parsed = None
            if exc.code in (429, 502, 503, 504) and attempt <= retries:
                time.sleep(5 * attempt)
                continue
            raise HttpError(exc.code, _error_message(parsed, raw)) from None
        except (urllib.error.URLError, TimeoutError, ConnectionError) as exc:
            if attempt <= retries:
                time.sleep(5 * attempt)
                continue
            raise HttpError(0, f"network error: {getattr(exc, 'reason', exc)}") from None


def raw_request(method: str, url: str, headers: dict[str, str] | None = None,
                timeout: float = 30.0) -> tuple[int, dict[str, str], str]:
    """Plain request for smoke tests: returns (status, lower-cased headers, body text); never raises on 4xx/5xx."""
    hdrs = {"User-Agent": USER_AGENT}
    hdrs.update(headers or {})
    req = urllib.request.Request(url, method=method, headers=hdrs)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status, {k.lower(): v for k, v in resp.headers.items()}, resp.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        return exc.code, {k.lower(): v for k, v in exc.headers.items()}, exc.read().decode("utf-8", "replace")
    except (urllib.error.URLError, TimeoutError, ConnectionError) as exc:
        return 0, {}, f"network error: {getattr(exc, 'reason', exc)}"


def poll(check, *, timeout: float, interval: float, what: str):
    """Call check() until it returns a truthy value or the timeout passes."""
    deadline = time.monotonic() + timeout
    while True:
        result = check()
        if result:
            return result
        if time.monotonic() >= deadline:
            die(f"timed out after {int(timeout)}s waiting for {what}")
        time.sleep(interval)
