"""initial schema + RLS lockdown

All tables live in ``public``. The browser never talks to Postgres (supabase-js is used
for the session only), so every table gets RLS **enabled with no policies** (deny-all
for PostgREST's anon/authenticated roles) and those roles lose all grants. The backend
connects as the table owner, which bypasses RLS.

Revision ID: 0001
Revises:
Create Date: 2026-10-07 05:56:03.289342
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = (
    "app_settings", "profiles", "people", "bills", "bill_items", "bill_charges", "bill_participants",
    "item_shares", "extraction_jobs", "receipt_files", "ocr_cache", "usage_events", "share_links",
)
API_ROLES = ("anon", "authenticated")


def _for_existing_roles(statement: str) -> str:
    """Wrap ``statement`` (with a ``{role}`` placeholder) so it only runs for roles that exist.
    Plain local Postgres has no Supabase roles; Supabase has both."""
    checks = "\n".join(
        f"  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '{role}') THEN EXECUTE '{statement.format(role=role)}'; END IF;"
        for role in API_ROLES
    )
    return f"DO $$\nBEGIN\n{checks}\nEND\n$$;"


def lock_down_table(table: str) -> None:
    op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")
    op.execute(_for_existing_roles(f"REVOKE ALL ON TABLE public.{table} FROM {{role}}"))


def revoke_api_role_defaults() -> None:
    op.execute(_for_existing_roles("REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM {role}"))
    for kind in ("TABLES", "SEQUENCES", "FUNCTIONS"):
        op.execute(_for_existing_roles(f"ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON {kind} FROM {{role}}"))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('global_monthly_page_cap', sa.Integer(), nullable=False),
    sa.Column('global_monthly_llm_budget_micros', sa.BigInteger(), nullable=False),
    sa.Column('default_user_quota', sa.Integer(), nullable=False),
    sa.Column('scans_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_user_quota >= 0', name=op.f('ck_app_settings_quota_nonneg')),
    sa.CheckConstraint('global_monthly_llm_budget_micros >= 0', name=op.f('ck_app_settings_budget_nonneg')),
    sa.CheckConstraint('global_monthly_page_cap >= 0', name=op.f('ck_app_settings_page_cap_nonneg')),
    sa.CheckConstraint('id = 1', name=op.f('ck_app_settings_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='member', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('monthly_scan_quota', sa.Integer(), server_default='30', nullable=False),
    sa.Column('default_currency', sa.String(length=3), server_default='SGD', nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("default_currency ~ '^[A-Z]{3}$'", name=op.f('ck_profiles_currency')),
    sa.CheckConstraint("role IN ('admin', 'member')", name=op.f('ck_profiles_role')),
    sa.CheckConstraint('monthly_scan_quota >= 0', name=op.f('ck_profiles_quota_nonneg')),
    sa.CheckConstraint('username = lower(username)', name=op.f('ck_profiles_username_lower')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('username', name=op.f('uq_profiles_username'))
    )
    op.create_table('ocr_cache',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('fk_ocr_cache_owner_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'content_sha256', name=op.f('pk_ocr_cache'))
    )
    op.create_table('people',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color_seed', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('is_self', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(name) BETWEEN 1 AND 60', name=op.f('ck_people_name_len')),
    sa.CheckConstraint('color_seed BETWEEN 0 AND 359', name=op.f('ck_people_color_seed')),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('fk_people_owner_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_people'))
    )
    op.create_index('ix_people_owner_id', 'people', ['owner_id'], unique=False)
    op.create_index('uq_people_owner_self', 'people', ['owner_id'], unique=True, postgresql_where=sa.text('is_self'))
    op.create_table('bills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('merchant', sa.Text(), nullable=True),
    sa.Column('bill_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('payer_person_id', sa.UUID(), nullable=True),
    sa.Column('subtotal_cents', sa.BigInteger(), nullable=True),
    sa.Column('grand_total_cents', sa.BigInteger(), nullable=True),
    sa.Column('tax_scenario', sa.Text(), nullable=True),
    sa.Column('receipt_meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_bills_currency')),
    sa.CheckConstraint("source IN ('scan', 'manual', 'quick')", name=op.f('ck_bills_source')),
    sa.CheckConstraint("status IN ('draft', 'scanning', 'review', 'assigning', 'complete')", name=op.f('ck_bills_status')),
    sa.CheckConstraint("tax_scenario IS NULL OR tax_scenario IN ('tax_exclusive', 'tax_inclusive', 'no_taxes')", name=op.f('ck_bills_tax_scenario')),
    sa.CheckConstraint('grand_total_cents IS NULL OR grand_total_cents >= 0', name=op.f('ck_bills_grand_total_nonneg')),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('fk_bills_owner_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_person_id'], ['people.id'], name=op.f('fk_bills_payer_person_id_people'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bills'))
    )
    op.create_index('ix_bills_owner_id_created_at', 'bills', ['owner_id', 'created_at'], unique=False)
    op.create_table('bill_charges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), server_default='other', nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('percent', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.CheckConstraint("kind IN ('tax', 'service', 'discount', 'rounding', 'other')", name=op.f('ck_bill_charges_kind')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_charges_bill_id_bills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_charges'))
    )
    op.create_index('ix_bill_charges_bill_id', 'bill_charges', ['bill_id'], unique=False)
    op.create_table('bill_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), server_default='1', nullable=False),
    sa.Column('unit_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('total_price_cents', sa.BigInteger(), nullable=False),
    sa.Column('split_mode', sa.Text(), nullable=True),
    sa.CheckConstraint("split_mode IS NULL OR split_mode IN ('single', 'equal', 'weighted', 'custom')", name=op.f('ck_bill_items_split_mode')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_items_bill_id_bills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_items'))
    )
    op.create_index('ix_bill_items_bill_id', 'bill_items', ['bill_id'], unique=False)
    op.create_table('bill_participants',
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_amount_cents', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_participants_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_bill_participants_person_id_people'), initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('bill_id', 'person_id', name=op.f('pk_bill_participants'))
    )
    op.create_index('ix_bill_participants_person_id', 'bill_participants', ['person_id'], unique=False)
    op.create_table('extraction_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('pages_billed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_micros', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('timings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'ocr', 'llm', 'validating', 'succeeded', 'needs_review', 'failed', 'cancelled')", name=op.f('ck_extraction_jobs_status')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_extraction_jobs_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('fk_extraction_jobs_owner_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_jobs')),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name=op.f('uq_extraction_jobs_owner_id_idempotency_key'))
    )
    op.create_index('ix_extraction_jobs_bill_id_created_at', 'extraction_jobs', ['bill_id', 'created_at'], unique=False)
    op.create_index('ix_extraction_jobs_status', 'extraction_jobs', ['status'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_share_links_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('fk_share_links_owner_id_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_share_links_person_id_people'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_links')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_share_links_token_hash'))
    )
    op.create_index('ix_share_links_bill_id', 'share_links', ['bill_id'], unique=False)
    op.create_table('item_shares',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('amount_cents', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('weight IS NULL OR weight >= 0', name=op.f('ck_item_shares_weight_nonneg')),
    sa.ForeignKeyConstraint(['bill_id', 'person_id'], ['bill_participants.bill_id', 'bill_participants.person_id'], name='fk_item_shares_participant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['bill_items.id'], name=op.f('fk_item_shares_item_id_bill_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'person_id', name=op.f('pk_item_shares'))
    )
    op.create_index('ix_item_shares_bill_id_person_id', 'item_shares', ['bill_id', 'person_id'], unique=False)
    op.create_table('receipt_files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bill_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_receipt_files_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], name=op.f('fk_receipt_files_job_id_extraction_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], name=op.f('fk_receipt_files_owner_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipt_files')),
    sa.UniqueConstraint('storage_path', name=op.f('uq_receipt_files_storage_path'))
    )
    op.create_index('ix_receipt_files_bill_id', 'receipt_files', ['bill_id'], unique=False)
    op.create_index('ix_receipt_files_expires_at', 'receipt_files', ['expires_at'], unique=False)
    op.create_index('ix_receipt_files_job_id', 'receipt_files', ['job_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('pages', sa.Integer(), server_default='0', nullable=False),
    sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cost_micros', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('ocr', 'llm')", name=op.f('ck_usage_events_kind')),
    sa.ForeignKeyConstraint(['job_id'], ['extraction_jobs.id'], name=op.f('fk_usage_events_job_id_extraction_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('fk_usage_events_user_id_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events'))
    )
    op.create_index('ix_usage_events_created_at', 'usage_events', ['created_at'], unique=False)
    op.create_index('ix_usage_events_user_id_created_at', 'usage_events', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    for table in (*TABLES, "alembic_version"):
        lock_down_table(table)
    revoke_api_role_defaults()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_events_user_id_created_at', table_name='usage_events')
    op.drop_index('ix_usage_events_created_at', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index('ix_receipt_files_job_id', table_name='receipt_files')
    op.drop_index('ix_receipt_files_expires_at', table_name='receipt_files')
    op.drop_index('ix_receipt_files_bill_id', table_name='receipt_files')
    op.drop_table('receipt_files')
    op.drop_index('ix_item_shares_bill_id_person_id', table_name='item_shares')
    op.drop_table('item_shares')
    op.drop_index('ix_share_links_bill_id', table_name='share_links')
    op.drop_table('share_links')
    op.drop_index('ix_extraction_jobs_status', table_name='extraction_jobs')
    op.drop_index('ix_extraction_jobs_bill_id_created_at', table_name='extraction_jobs')
    op.drop_table('extraction_jobs')
    op.drop_index('ix_bill_participants_person_id', table_name='bill_participants')
    op.drop_table('bill_participants')
    op.drop_index('ix_bill_items_bill_id', table_name='bill_items')
    op.drop_table('bill_items')
    op.drop_index('ix_bill_charges_bill_id', table_name='bill_charges')
    op.drop_table('bill_charges')
    op.drop_index('ix_bills_owner_id_created_at', table_name='bills')
    op.drop_table('bills')
    op.drop_index('uq_people_owner_self', table_name='people', postgresql_where=sa.text('is_self'))
    op.drop_index('ix_people_owner_id', table_name='people')
    op.drop_table('people')
    op.drop_table('ocr_cache')
    op.drop_table('profiles')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
